# Numpy

## Theoretical Questions:

### Que 1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it enhance Python's capabilities for numerical operations?

### Answer 1
NumPy, short for Numerical Python, is a fundamental library in Python for scientific computing and data analysis. It provides powerful data structures and functions that enhance Python's capabilities for numerical operations. Here’s a closer look at its purpose and advantages:

#### Purpose of NumPy
1. **Array Computing**: At its core, NumPy introduces the `ndarray`, a powerful N-dimensional array object that allows for efficient storage and manipulation of large datasets.
2. **Numerical Operations**: It facilitates mathematical operations on arrays, including element-wise operations, linear algebra, statistical operations, and more.
3. **Interoperability**: NumPy serves as a foundational library that many other scientific libraries (like SciPy, Pandas, and Matplotlib) build upon, making it crucial for scientific workflows in Python.

#### Advantages of NumPy

1. **Performance**:
   - **Efficiency**: NumPy arrays are more efficient than Python lists for numerical data because they store data in contiguous blocks of memory. This leads to faster access and processing.
   - **Vectorization**: Operations on NumPy arrays are vectorized, which means they can be executed in compiled code rather than interpreted Python, significantly speeding up calculations.

2. **Convenience**:
   - **Rich Functionality**: NumPy comes with a wide range of mathematical functions for performing operations on arrays, from basic arithmetic to more complex linear algebra and statistical functions.
   - **Broadcasting**: This feature allows operations to be performed on arrays of different shapes, making it easier to write cleaner and more intuitive code.

3. **Flexibility**:
   - **Multi-dimensional Support**: NumPy can handle arrays of any dimension, enabling complex data manipulation and mathematical modeling.
   - **Data Types**: It supports a variety of data types, including integers, floats, and more complex types, allowing users to choose the appropriate type for their specific application.

4. **Integration**:
   - **Compatibility with Other Libraries**: NumPy arrays are compatible with a variety of other Python libraries, facilitating smooth integration in data analysis pipelines.
   - **C and Fortran Integration**: NumPy allows for easy integration with C and Fortran code, which is beneficial for performance-critical applications.

5. **Community and Documentation**:
   - **Strong Community**: Being widely used in the scientific community, there is a wealth of resources, documentation, and community support available.
   - **Extensive Documentation**: The well-maintained documentation makes it easier for newcomers to learn and use the library effectively.

#### Enhancements to Python’s Capabilities

- **Speed and Efficiency**: NumPy’s array operations are implemented in C, allowing for execution speeds that are typically much faster than pure Python code.
- **Ease of Use**: It provides a straightforward syntax for complex mathematical operations, reducing the learning curve for those familiar with array-based programming languages like MATLAB.
- **Data Manipulation**: NumPy simplifies data manipulation, enabling tasks like reshaping, slicing, and aggregating data with minimal code.

In summary, NumPy enhances Python's capabilities for numerical operations by providing efficient, flexible, and easy-to-use data structures and functions, making it an essential tool for scientific computing and data analysis.

### Que 2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the other??

### Answer
Both np.mean() and np.average() are functions in NumPy used to compute the average of elements in an array, but they have some important differences in functionality and use cases. Here’s a detailed comparison:

#### Purpose: 
Computes the arithmetic mean (average) of the elements along a specified axis.
#### Usage: 
Generally straightforward; you simply pass the array and optionally specify the axis.
#### Syntax:

np.mean(a, axis=None, dtype=None, out=None, keepdims=False)

#### Weighting: 
Does not support weighting; every element contributes equally to the mean.
np.average()
#### Purpose: 
Computes the weighted average of the elements, allowing for the incorporation of weights for different elements.
#### Usage: 
More flexible than np.mean(), as it allows you to specify an array of weights.
#### Syntax:

np.average(a, axis=None, weights=None, returned=False)


#### Weighting: 
Supports weighting; if weights are provided, they determine the contribution of each element to the average. If weights are not provided, it behaves like np.mean().
### Key Differences
#### Functionality:

np.mean() calculates a simple arithmetic mean without any weights.
np.average() can calculate a weighted average when weights are specified, making it more versatile in certain scenarios.
#### Performance:

Both functions are generally efficient, but np.mean() is often slightly faster since it performs a straightforward calculation without the overhead of handling weights.
#### Input Requirements:

np.mean() only requires the input array.
np.average() requires the input array and optionally a weights array, which can lead to more complex use cases.
When to Use Each
#### Use np.mean():

When you simply need the average of a dataset without considering weights.
In most general-purpose scenarios where a simple mean is sufficient.
#### Use np.average():

When dealing with datasets where different elements should contribute unequally to the average (e.g., in a situation where you have grades with different credit hours).
When you need to include a specific weighting factor that impacts the result.
### Example
Here's a quick example to illustrate the difference:

In [7]:
import numpy as np

data = np.array([1, 2, 3, 4])

# Simple mean
mean_value = np.mean(data)  # Outputs: 2.5

# Weighted average
weights = np.array([1, 2, 3, 4])
weighted_average = np.average(data, weights=weights)

In this example, np.mean() provides the arithmetic mean, while np.average() takes into account the weights associated with each element, resulting in a different average.

### Que 3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D arrays.

### Answer
Reversing a NumPy array can be done along different axes using various methods. Here’s how you can reverse 1D and 2D arrays in NumPy:

Reversing a 1D Array
For a 1D array, reversing can be done using slicing:

### Example

In [8]:
import numpy as np

# Create a 1D array
arr_1d = np.array([1, 2, 3, 4, 5])

# Reverse the array
reversed_arr_1d = arr_1d[::-1]

print("Original 1D array:", arr_1d)
print("Reversed 1D array:", reversed_arr_1d)

Original 1D array: [1 2 3 4 5]
Reversed 1D array: [5 4 3 2 1]


Reversing a 2D Array
For a 2D array, you can reverse along specific axes (0 for rows, 1 for columns). You can use slicing in a similar manner.

### Example: 
Reverse along axis 0 (rows)

In [11]:
# Create a 2D array
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Reverse along axis 0 (rows)
reversed_arr_2d_axis0 = arr_2d[::-1]

print("Original 2D array:\n", arr_2d)
print("Reversed 2D array along axis 0:\n", reversed_arr_2d_axis0)

Original 2D array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Reversed 2D array along axis 0:
 [[7 8 9]
 [4 5 6]
 [1 2 3]]


### Example: 
Reverse along axis 1 (columns)

# Reverse along axis 1 (columns)
reversed_arr_2d_axis1 = arr_2d[:, ::-1]

print("Reversed 2D array along axis 1:\n", reversed_arr_2d_axis1)

#### Summary of Methods
##### 1D Arrays: 
Use slicing [::-1] to reverse the entire array.
##### 2D Arrays: 
###### Use slicing:
[::-1] to reverse along axis 0 (rows).
[:, ::-1] to reverse along axis 1 (columns).
These methods provide a straightforward way to manipulate array orientations in NumPy.

### Que 4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types in memory management and performance..



### Answer
To determine the data type of elements in a NumPy array, you can use the .dtype attribute. This attribute provides information about the type of data stored in the array.

Determining the Data Type
#### Example
Here’s a quick example of how to check the data type of a NumPy array:

In [12]:
import numpy as np

# Create a NumPy array
arr = np.array([1, 2, 3, 4])

# Determine the data type
data_type = arr.dtype

print("Data type of the array:", data_type)

Data type of the array: int32


You can also check the data type of more complex arrays:

In [13]:
# Create an array with floats
arr_float = np.array([1.0, 2.0, 3.0])
print("Data type of the float array:", arr_float.dtype)  # Output: float64

# Create an array with complex numbers
arr_complex = np.array([1 + 2j, 3 + 4j])
print("Data type of the complex array:", arr_complex.dtype) 

Data type of the float array: float64
Data type of the complex array: complex128


### Importance of Data Types
#### Memory Management:

##### Efficient Storage:
Different data types consume different amounts of memory. For example, int8 takes 1 byte, int16 takes 2 bytes, and int64 takes 8 bytes. Choosing the appropriate type helps manage memory efficiently, especially in large datasets.
Avoiding Overhead: Using unnecessarily large data types can lead to wasted memory, which is critical in resource-constrained environments or when handling large-scale data.
#### Performance:

##### Computation Speed: 
Operations on smaller data types (like float32 instead of float64) can be faster due to reduced memory bandwidth requirements. This is particularly important for performance-sensitive applications, such as numerical simulations and data analysis.
Vectorization: NumPy leverages vectorized operations for efficiency. Using the right data types allows these operations to be optimized by the underlying libraries (like BLAS or LAPACK), leading to significant speed improvements.
Precision and Range:

##### Accuracy of Calculations: 
Different data types offer different ranges and precision levels. For example, floating-point types (float32 vs. float64) have different precision, which can affect the outcome of calculations, particularly in iterative algorithms.
Avoiding Overflow/Underflow: Using data types with appropriate ranges can help avoid issues like overflow or underflow in calculations.
#### Interoperability:

##### Compatibility with Other Libraries:
Different Python libraries expect specific data types. Using the correct type ensures smooth integration and compatibility when passing data between libraries, such as NumPy, Pandas, or machine learning frameworks.
### Summary
In summary, you can determine the data type of elements in a NumPy array using the .dtype attribute. The importance of data types extends to efficient memory management, performance optimization, accuracy in calculations, and interoperability with other libraries. Choosing the appropriate data type is crucial for maximizing the efficiency and effectiveness of your numerical computations in Python.





### Que 5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?

### Answer
In NumPy, ndarrays (n-dimensional arrays) are the core data structure used for numerical computations. They provide a way to store and manipulate large datasets efficiently. Here’s an overview of their key features and how they differ from standard Python lists.

### Key Features of ndarrays
#### Homogeneous Data Types:

All elements in an ndarray must be of the same data type, which allows for more efficient memory usage and faster computations.
#### Multi-dimensional Support:

ndarrays can have any number of dimensions (1D, 2D, 3D, etc.), enabling complex data structures like matrices, tensors, and higher-dimensional arrays.
#### Efficient Memory Layout:

ndarrays use contiguous blocks of memory, which enhances performance during computations. This memory layout allows for efficient access and manipulation of elements.
#### Vectorized Operations:

NumPy allows for element-wise operations on ndarrays, meaning you can perform arithmetic operations on entire arrays without writing explicit loops. This leads to concise and efficient code.
#### Broadcasting:

Broadcasting is a powerful feature that allows NumPy to perform operations on arrays of different shapes, expanding smaller arrays as needed to match the dimensions of larger ones.
#### Rich Functionality:

NumPy provides a vast array of built-in functions for mathematical operations, linear algebra, statistics, and more, making it a comprehensive library for scientific computing.
#### Indexing and Slicing:

ndarrays support advanced indexing and slicing techniques, enabling flexible data manipulation and extraction.
Integration with Other Libraries:

ndarrays serve as the foundation for many other scientific libraries in Python, such as SciPy, Pandas, and Matplotlib, facilitating seamless data analysis and visualization.
### Differences from Standard Python Lists
#### Data Type Consistency:

#### ndarrays: 
All elements must be of the same type (e.g., all integers or all floats).
#### Python Lists: 
Can contain elements of different types (e.g., integers, floats, strings).
### Performance:

#### ndarrays: 
More memory-efficient and faster for numerical operations due to their contiguous memory layout and optimized performance for vectorized operations.
#### Python Lists: 
Generally slower for numerical computations, as they are not optimized for such operations and require more memory overhead for heterogeneous data.
#### Dimensionality:

#### ndarrays: 
Can easily represent multi-dimensional data structures (e.g., 2D matrices, 3D tensors).
#### Python Lists: 
Can represent multi-dimensional data, but this often requires nesting lists (e.g., a list of lists) and is less efficient and convenient for mathematical operations.
#### Functionality:

#### ndarrays: 
Equipped with a rich set of functions for mathematical and statistical operations, making them suitable for scientific computing.
#### Python Lists: 
Lack specialized numerical operations; you need to implement such functionality manually or use external libraries.
### Example Comparison
Using a Python List

In [14]:
# Python list
py_list = [1, 2, 3, 4]
# Adding 1 to each element requires a loop
py_list_incremented = [x + 1 for x in py_list]
print(py_list_incremented)

[2, 3, 4, 5]


Using a NumPy ndarray

In [15]:
import numpy as np

# NumPy ndarray
np_array = np.array([1, 2, 3, 4])
# Adding 1 to each element using vectorization
np_array_incremented = np_array + 1
print(np_array_incremented) 

[2 3 4 5]


### Summary
In summary, ndarrays are powerful, multi-dimensional arrays in NumPy that provide significant advantages over standard Python lists for numerical computations. They ensure homogeneous data types, efficient memory usage, and support for advanced mathematical operations, making them essential for scientific computing and data analysis.





### Que 6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.

### Answer
NumPy arrays offer several performance benefits over standard Python lists, particularly for large-scale numerical operations. Here are the key advantages that contribute to improved performance:

### 1. Contiguous Memory Allocation
Memory Layout: NumPy arrays are stored in contiguous blocks of memory. This layout enhances cache coherence and allows for more efficient access patterns compared to Python lists, which store references to objects scattered in memory.
Lower Overhead: Each element in a NumPy array is stored in a fixed-size format, leading to lower memory overhead compared to Python lists, which store pointers to objects.
### 2. Homogeneous Data Types
Type Consistency: NumPy arrays require all elements to be of the same data type, which allows for optimized memory usage and faster computation. Python lists can contain mixed data types, leading to additional overhead when accessing and manipulating elements.
Type-Specific Operations: Operations on homogeneous data types can be optimized at a low level, resulting in faster execution.
### 3. Vectorized Operations
Element-Wise Operations: NumPy allows for vectorized operations, meaning you can perform arithmetic and mathematical operations on entire arrays without explicit loops. This reduces the overhead of Python’s interpreted loops and leverages optimized C and Fortran libraries.
Performance Gains: Vectorization can lead to significant performance improvements—operations on large datasets can be several times faster than equivalent operations on Python lists.
### 4. Broadcasting
Flexible Operations: NumPy's broadcasting rules allow operations on arrays of different shapes without the need for explicit replication of data. This feature simplifies code and avoids the memory overhead associated with creating temporary arrays.
Efficiency: Broadcasting minimizes the need for additional memory allocation and copying, which is particularly beneficial when dealing with large datasets.
### 5. Optimized Functions
Built-in Mathematical Functions: NumPy provides a wide range of optimized functions for mathematical operations (e.g., linear algebra, statistics, Fourier transforms). These functions are implemented in low-level languages like C and are optimized for performance.
Avoiding Python Overhead: By using these functions, you can avoid the overhead associated with Python function calls and loops.
### 6. Parallelism and Multithreading
Internal Optimization: Many NumPy operations are internally optimized to take advantage of parallel processing capabilities of modern CPUs. Libraries like BLAS and LAPACK, which NumPy relies on for linear algebra operations, often use multithreading to speed up computations.
Scalability: This means that as your data scales, NumPy can leverage the hardware capabilities more effectively than Python lists.
### 7. Efficient I/O Operations
File Handling: NumPy offers efficient methods for reading from and writing to files (e.g., using np.loadtxt() or np.save()), which are faster than iterating through Python lists and performing I/O operations.
### Example Comparison
Here's a simple example that highlights the performance difference when summing large datasets:

In [16]:
import numpy as np
import time

# Create a large array
size = 10**7

# Using NumPy
np_array = np.arange(size)
start_time = time.time()
np_sum = np.sum(np_array)
print("NumPy sum:", np_sum)
print("NumPy execution time:", time.time() - start_time)

# Using Python list
py_list = list(range(size))
start_time = time.time()
py_sum = sum(py_list)
print("Python list sum:", py_sum)
print("Python list execution time:", time.time() - start_time)

NumPy sum: -2014260032
NumPy execution time: 0.0
Python list sum: 49999995000000
Python list execution time: 0.5576517581939697


In this example, you would typically observe that the NumPy array sum is significantly faster than the Python list sum due to the reasons outlined above.

### Summary
In summary, the performance benefits of NumPy arrays over Python lists for large-scale numerical operations include contiguous memory allocation, homogeneous data types, vectorized operations, broadcasting, optimized built-in functions, and efficient I/O handling. These advantages make NumPy a crucial tool for scientific computing, data analysis, and any application requiring efficient numerical computation.

### Que 7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and output..

### Answer 
In NumPy, vstack() and hstack() are functions used to stack arrays vertically and horizontally, respectively. Here's a detailed comparison along with examples demonstrating their usage.

numpy.vstack()
##### Purpose: 
Stacks arrays in sequence vertically (row-wise).
##### Input: 
Arrays must have the same number of columns.

Example of vstack()

In [1]:
import numpy as np

# Create two 2D arrays
arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])

arr2 = np.array([[7, 8, 9],
                 [10, 11, 12]])

# Stack the arrays vertically
result_vstack = np.vstack((arr1, arr2))

print("Result of vstack:")
print(result_vstack)

Result of vstack:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


numpy.hstack()
##### Purpose: 
Stacks arrays in sequence horizontally (column-wise).
##### Input: 
Arrays must have the same number of rows.

Example of hstack()

In [18]:
# Stack the arrays horizontally
result_hstack = np.hstack((arr1, arr2))

print("Result of hstack:")
print(result_hstack)

Result of hstack:
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


### Summary of Differences
Orientation:

vstack(): Stacks arrays vertically, increasing the number of rows.

hstack(): Stacks arrays horizontally, increasing the number of columns.

Input Requirements:

For vstack(): Arrays must have the same number of columns.

For hstack(): Arrays must have the same number of rows.

These functions are particularly useful for assembling datasets and organizing data into a desired shape for further analysis or manipulation.

### Que 8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various array dimensions.
.

### Answer
In NumPy, the fliplr() and flipud() methods are used to flip arrays along specific axes, but they differ in the direction of the flipping. Here’s a detailed explanation of each method, including their effects on various array dimensions.

numpy.fliplr()
##### Purpose: 
Flips an array left to right (horizontally).
##### Effect: 
It reverses the order of the columns in a 2D array, effectively flipping it along the vertical axis.
##### Applicable Dimensions: 
Primarily used with 2D arrays, but can also be applied to higher-dimensional arrays by treating each 2D slice independently.

Example of fliplr()

In [19]:
import numpy as np

# Create a 2D array
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Flip the array left to right
flipped_lr = np.fliplr(arr_2d)

print("Original array:")
print(arr_2d)
print("\nFlipped left to right:")
print(flipped_lr)

Original array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Flipped left to right:
[[3 2 1]
 [6 5 4]
 [9 8 7]]


numpy.flipud()
##### Purpose: 
Flips an array up to down (vertically).
##### Effect: 
It reverses the order of the rows in a 2D array, effectively flipping it along the horizontal axis.
##### Applicable Dimensions: 
Primarily used with 2D arrays, but can also be applied to higher-dimensional arrays by treating each 2D slice independently.

Example of flipud()

In [20]:
# Flip the array up to down
flipped_ud = np.flipud(arr_2d)

print("\nFlipped up to down:")
print(flipped_ud)


Flipped up to down:
[[7 8 9]
 [4 5 6]
 [1 2 3]]


### Summary of Differences
#### Direction of Flipping:

##### fliplr(): 
Flips the array horizontally (left to right), affecting the columns.
##### flipud(): 
Flips the array vertically (up to down), affecting the rows.
##### Effect on Array Dimensions:

#### 2D Arrays:
fliplr() reverses the columns of the array.

flipud() reverses the rows of the array.

##### Higher-Dimensional Arrays: 
Both functions can be applied, but they operate independently on each 2D slice within the higher-dimensional structure.

### Conclusion
In summary, np.fliplr() and np.flipud() are useful for manipulating the orientation of arrays. Understanding their effects is important for data preprocessing and transformation tasks in numerical computing.

### Que 9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?

### Answer
The array_split() method in NumPy is used to split an array into multiple sub-arrays along a specified axis. It is particularly useful when you need to divide a large dataset into smaller, more manageable chunks.

Key Features of array_split()
##### 
Flexible Splitting:

You can specify the number of splits or the indices at which to split the array.
##### 
Handles Uneven Splits:

Unlike the split() method, which requires the splits to be evenly sized, array_split() allows for uneven splits. If the array cannot be evenly divided, the remaining elements are distributed among the resulting sub-arrays.
##### Axis Specification:

You can specify the axis along which to split the array. The default is the first axis (0).

#### Function Signature

numpy.array_split(ary, indices_or_sections, axis=0)

##### ary: 
The array to be split.
##### indices_or_sections: 
Either the number of sections to split into or the indices at which to split the array.
##### axis: 
The axis along which to split (default is 0).
#### Examples
#### Example 1: 
Even Splits

In [22]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Split into 3 equal parts
split_even = np.array_split(arr, 3)

print("Split into 3 parts:")
for part in split_even:
    print(part)

Split into 3 parts:
[1 2 3]
[4 5 6]
[7 8 9]


#### Example 2: 
Uneven Splits

In [24]:
# Split into 4 parts
split_uneven = np.array_split(arr, 4)

print("\nSplit into 4 parts:")
for part in split_uneven:
    print(part)


Split into 4 parts:
[1 2 3]
[4 5]
[6 7]
[8 9]


#### Explanation of Uneven Splits
In the second example, when we attempt to split the array into 4 parts, NumPy divides the array as evenly as possible:

The first sub-array gets 3 elements.
The second and third sub-arrays get 2 elements each.
The last sub-array gets the remaining elements.
This functionality is particularly useful in data preprocessing tasks where datasets may not be evenly divisible, allowing for flexible handling of such cases.

### Summary
The array_split() method in NumPy is a powerful tool for dividing arrays into sub-arrays, with the ability to handle uneven splits gracefully. This flexibility makes it suitable for various applications in data analysis and manipulation, enabling efficient data handling regardless of the original array size.





### Que 10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array operations?

### Answer
Vectorization and broadcasting are two fundamental concepts in NumPy that significantly enhance the efficiency and performance of array operations. Here’s an overview of each concept and their contributions to efficient computing.

#### Vectorization
##### Definition: 
Vectorization refers to the process of applying operations to entire arrays (or large chunks of data) rather than using explicit loops to process individual elements. This is possible in NumPy because it leverages highly optimized C and Fortran libraries for numerical computations, allowing operations to be performed at a lower level.

#### Benefits:

##### Performance Improvement: 
Vectorized operations are typically much faster than their loop-based counterparts due to lower overhead from Python's interpreted nature.
##### Cleaner Code: 
Vectorization leads to more concise and readable code, reducing the likelihood of errors that may occur in complex looping structures.
##### Parallelism: 
Many vectorized operations can be parallelized, taking advantage of modern CPU architectures and multi-threading, further enhancing performance.
##### Example: 
Instead of using a loop to add two arrays element-wise, you can directly use vectorized operations:

In [25]:
import numpy as np

# Create two large arrays
a = np.arange(1, 1000001)
b = np.arange(1000000, 0, -1)

# Vectorized addition
c = a + b

In this example, a + b is a vectorized operation that adds the two arrays element-wise without the need for a loop.

#### Broadcasting
##### Definition: 
Broadcasting is a powerful mechanism that allows NumPy to perform arithmetic operations on arrays of different shapes. It automatically expands the smaller array(s) to match the shape of the larger array during operations.

##### How It Works: 
When performing operations on arrays with different shapes:

NumPy compares the dimensions of the two arrays.
If the dimensions are not the same, NumPy "stretches" the smaller array along the axis with fewer dimensions by repeating its elements to match the shape of the larger array.
The operation is then applied element-wise.
#### Benefits:

##### Flexible Array Operations: 
Broadcasting allows for operations between arrays of different shapes without the need to manually reshape or replicate data.
##### Memory Efficiency: 
Instead of creating large intermediate arrays, broadcasting efficiently uses the existing smaller arrays, reducing memory overhead.
#### Example:

In [26]:
# Create a 2D array and a 1D array
a = np.array([[1, 2, 3],
              [4, 5, 6]])

b = np.array([10, 20, 30])

# Broadcasting addition
result = a + b

print(result)

[[11 22 33]
 [14 25 36]]


In this example, the 1D array b is broadcasted to match the shape of the 2D array a, allowing for element-wise addition.

### Summary of Contributions to Efficient Array Operations
##### Speed: 
Vectorization allows for faster computations by minimizing the overhead of Python loops and taking advantage of low-level optimizations.
##### Simplicity: 
Both vectorization and broadcasting enable cleaner, more readable code, making it easier to implement complex operations without cumbersome syntax.
##### Reduced Memory Usage: 
Broadcasting minimizes the need for creating large temporary arrays, which conserves memory and speeds up operations.

Together, vectorization and broadcasting make NumPy a powerful tool for scientific computing, enabling efficient and flexible manipulation of large datasets. These features are essential for tasks in data analysis, machine learning, and numerical simulations.

## Practical Questions:

### Que 1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

### Answer
You can create a 3x3 NumPy array with random integers between 1 and 100 and then interchange its rows and columns using the numpy.random.randint() function and the numpy.transpose() method or the .T attribute. Here’s how you can do it:

### Step-by-Step Code

In [2]:
import numpy as np

# Create a 3x3 array with random integers between 1 and 100
array_3x3 = np.random.randint(1, 101, size=(3, 3))
print("Original array:")
print(array_3x3)

# Interchange rows and columns (transpose the array)
transposed_array = array_3x3.T
print("\nTransposed array:")
print(transposed_array)

Original array:
[[41 61  2]
 [74 55 85]
 [86 47 67]]

Transposed array:
[[41 74 86]
 [61 55 47]
 [ 2 85 67]]


### Explanation
##### np.random.randint(1, 101, size=(3, 3)): 
This function generates a 3x3 array of random integers between 1 and 100.
##### array_3x3.T: 
This is the transposition operation that interchanges rows and columns of the original array. You can also use np.transpose(array_3x3) for the same effect.
You now have a 3x3 NumPy array with its rows and columns interchanged!

### Que 2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

### Answer
You can generate a 1D NumPy array with 10 elements and then reshape it into a 2x5 array and a 5x2 array using the numpy.reshape() method. Here’s how to do it step by step:

### Step-by-Step Code

In [3]:
import numpy as np

# Generate a 1D NumPy array with 10 elements
array_1d = np.arange(10)  # Creates an array with values from 0 to 9
print("Original 1D array:")
print(array_1d)

# Reshape it into a 2x5 array
array_2x5 = array_1d.reshape(2, 5)
print("\nReshaped into 2x5 array:")
print(array_2x5)

# Reshape it into a 5x2 array
array_5x2 = array_1d.reshape(5, 2)
print("\nReshaped into 5x2 array:")
print(array_5x2)

Original 1D array:
[0 1 2 3 4 5 6 7 8 9]

Reshaped into 2x5 array:
[[0 1 2 3 4]
 [5 6 7 8 9]]

Reshaped into 5x2 array:
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


### Explanation
##### np.arange(10): 
This function generates a 1D array with values from 0 to 9.
##### array_1d.reshape(2, 5): 
This reshapes the original 1D array into a 2x5 array.
##### array_1d.reshape(5, 2): 
This reshapes the original 1D array into a 5x2 array.
Reshaping is possible because the total number of elements remains constant (10 elements in total), and the new shape must be compatible with the original array's size.

### Que 3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

### Answer
You can create a 4x4 NumPy array with random float values and then add a border of zeros around it to create a 6x6 array using the numpy.pad() function. Here’s how to do it step by step:

### Step-by-Step Code

In [4]:
import numpy as np

# Create a 4x4 array with random float values
array_4x4 = np.random.random((4, 4))
print("Original 4x4 array:")
print(array_4x4)

# Add a border of zeros around the array
array_with_border = np.pad(array_4x4, pad_width=1, mode='constant', constant_values=0)
print("\n6x6 array with border of zeros:")
print(array_with_border)

Original 4x4 array:
[[0.53277516 0.03181958 0.13918648 0.47239566]
 [0.06743509 0.32720059 0.25114418 0.03238935]
 [0.3489738  0.32163591 0.16721836 0.41629387]
 [0.99698153 0.72914658 0.03818786 0.50615591]]

6x6 array with border of zeros:
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.53277516 0.03181958 0.13918648 0.47239566 0.        ]
 [0.         0.06743509 0.32720059 0.25114418 0.03238935 0.        ]
 [0.         0.3489738  0.32163591 0.16721836 0.41629387 0.        ]
 [0.         0.99698153 0.72914658 0.03818786 0.50615591 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


### Explanation
np.random.random((4, 4)): This function generates a 4x4 array filled with random float values between 0 and 1.
np.pad(array_4x4, pad_width=1, mode='constant', constant_values=0): This adds a border of zeros around the original array. The pad_width=1 specifies that a border of 1 element should be added on all sides, mode='constant' indicates that the padding should be filled with a constant value, and constant_values=0 specifies that the constant value to use for padding is 0.

This results in a 6x6 array with the original values in the center and a border of zeros surrounding them.

### Que 4. Using NumPy, create an array of integers from 10 to 60 with a step of 5

### Answer
You can create an array of integers from 10 to 60 with a step of 5 using the numpy.arange() function. Here’s how to do it:

### Step-by-Step Code

In [5]:
import numpy as np

# Create an array of integers from 10 to 60 with a step of 5
array_integers = np.arange(10, 61, 5)
print("Array of integers from 10 to 60 with a step of 5:")
print(array_integers)

Array of integers from 10 to 60 with a step of 5:
[10 15 20 25 30 35 40 45 50 55 60]


### Explanation
np.arange(10, 61, 5): This function generates an array of integers starting from 10 up to (but not including) 61, incrementing by 5 at each step. Since we want to include 60 in the array, the endpoint is set to 61.

This results in an array containing the integers: 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, and 60.

### Que 5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element.


### Answer
You can create a NumPy array of strings and then apply various case transformations such as uppercase, lowercase, title case, and more using string methods available in NumPy. Here’s how to do it:

### Step-by-Step Code

In [6]:
import numpy as np

# Create a NumPy array of strings
array_strings = np.array(['python', 'numpy', 'pandas'])

# Apply different case transformations
uppercase_array = np.char.upper(array_strings)
lowercase_array = np.char.lower(array_strings)
titlecase_array = np.char.title(array_strings)
capitalize_array = np.char.capitalize(array_strings)

# Display the results
print("Original array:")
print(array_strings)

print("\nUppercase:")
print(uppercase_array)

print("\nLowercase:")
print(lowercase_array)

print("\nTitle case:")
print(titlecase_array)

print("\nCapitalize:")
print(capitalize_array)

Original array:
['python' 'numpy' 'pandas']

Uppercase:
['PYTHON' 'NUMPY' 'PANDAS']

Lowercase:
['python' 'numpy' 'pandas']

Title case:
['Python' 'Numpy' 'Pandas']

Capitalize:
['Python' 'Numpy' 'Pandas']


### Explanation
##### np.char.upper(array_strings): 
Converts all elements of the array to uppercase.
##### np.char.lower(array_strings): 
Converts all elements of the array to lowercase.
##### np.char.title(array_strings): 
Converts each element to title case (first letter capitalized).
##### np.char.capitalize(array_strings): 
Capitalizes the first letter of each element while making the rest lowercase.

These transformations showcase the flexibility of handling string data in NumPy using its character operations.

### Que 6. Generate a NumPy array of words. Insert a space between each character of every word in the array.

### Answer
You can generate a NumPy array of words and then insert a space between each character of every word using NumPy's string operations. Here’s how to do it:

### Step-by-Step Code

In [8]:
import numpy as np

# Create a NumPy array of words
array_words = np.array(['hello', 'world', 'numpy', 'python'])

# Insert a space between each character of every word
spaced_words = np.char.join(' ', array_words)

# Display the results
print("Original array:")
print(array_words)

print("\nWords with spaces between characters:")
for word in spaced_words:
    print(word)

Original array:
['hello' 'world' 'numpy' 'python']

Words with spaces between characters:
h e l l o
w o r l d
n u m p y
p y t h o n


### Explanation
np.array(['hello', 'world', 'numpy', 'python']): This creates a NumPy array of words.
np.char.join(' ', array_words): This method joins each character of the words with a space. Each word in the array is treated as a string, and the space character is inserted between each character.

The result is an array where each word has spaces between its characters, making it easy to read.

### Que 7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

### Answer
You can create two 2D NumPy arrays and then perform element-wise operations such as addition, subtraction, multiplication, and division. Here’s how to do it step by step:

### Step-by-Step Code

In [9]:
import numpy as np

# Create two 2D NumPy arrays
array1 = np.array([[1, 2, 3],
                   [4, 5, 6]])

array2 = np.array([[10, 20, 30],
                   [40, 50, 60]])

# Perform element-wise addition
addition = array1 + array2

# Perform element-wise subtraction
subtraction = array1 - array2

# Perform element-wise multiplication
multiplication = array1 * array2

# Perform element-wise division
division = array1 / array2

# Display the results
print("Array 1:")
print(array1)

print("\nArray 2:")
print(array2)

print("\nElement-wise Addition:")
print(addition)

print("\nElement-wise Subtraction:")
print(subtraction)

print("\nElement-wise Multiplication:")
print(multiplication)

print("\nElement-wise Division:")
print(division)

Array 1:
[[1 2 3]
 [4 5 6]]

Array 2:
[[10 20 30]
 [40 50 60]]

Element-wise Addition:
[[11 22 33]
 [44 55 66]]

Element-wise Subtraction:
[[ -9 -18 -27]
 [-36 -45 -54]]

Element-wise Multiplication:
[[ 10  40  90]
 [160 250 360]]

Element-wise Division:
[[0.1 0.1 0.1]
 [0.1 0.1 0.1]]


### Explanation
#### array1 and array2: 
Two 2D arrays are created.
Element-wise Operations:
##### Addition: 
array1 + array2 adds corresponding elements.
##### Subtraction: 
array1 - array2 subtracts corresponding elements.
##### Multiplication: 
array1 * array2 multiplies corresponding elements.
##### Division: 
array1 / array2 divides corresponding elements, resulting in a float array.
These operations are performed element-wise, meaning that each operation is applied to the corresponding elements of the two arrays.

### Que 8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

### Answer

In [1]:
import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.eye(5)

# Extract the diagonal elements
diagonal_elements = np.diag(identity_matrix)

# Output the results
print("Identity Matrix:\n", identity_matrix)
print("Diagonal Elements:", diagonal_elements)

Identity Matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Diagonal Elements: [1. 1. 1. 1. 1.]


#### Explanation:
- np.eye(5) creates a 5x5 identity matrix.
- np.diag(identity_matrix) retrieves the diagonal elements of the matrix.

The output will show the identity matrix and the diagonal elements, which will all be 1.

### Que 9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.
.

### Answer
To generate a NumPy array of 100 random integers between 0 and 1000 and then find and display all prime numbers in that array, you can use the following code:

In [2]:
import numpy as np

# Generate a NumPy array of 100 random integers between 0 and 1000
random_integers = np.random.randint(0, 1000, size=100)

# Function to check if a number is prime
def is_prime(num):
    if num <= 1:
        return False
    for i in range(2, int(num**0.5) + 1):
        if num % i == 0:
            return False
    return True

# Find all prime numbers in the array
prime_numbers = [num for num in random_integers if is_prime(num)]

print("Random Integers:\n", random_integers)
print("Prime Numbers:", prime_numbers)

Random Integers:
 [886 207 754 503 571 177 554 287 796 727 656 686 550 481 724 822 515 679
 913 227 706  52 968 350 383 853 746  15 650 239 146 180 594 841 799 442
 328 754 817 837 949 578 773 158 406 712 703 910  30 958 935 407 560 675
 919 424 398 713 912 471 516 201 906 820 696 531 420 661 681 926 471 375
 545 847 206 128 114 851 418 155 428 511 817 457  40 134 531 241 810 945
 983 894 605 730 993 315  61  69 768 617]
Prime Numbers: [503, 571, 727, 227, 383, 853, 239, 773, 919, 661, 457, 241, 983, 61, 617]


#### Explanation:
1. np.random.randint(0, 1000, size=100) generates an array of 100 random integers between 0 and 1000.
2. The is_prime function checks if a given number is prime.
3. A list comprehension is used to filter out prime numbers from the array.
4. Finally, the random integers and the identified prime numbers are printed.

You can run this code to see the random integers and the prime numbers found within them.

### Que 10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.


### Answer
#### Step 1: Create the NumPy array
Let's assume we have temperatures for a month (30 days). We'll generate some random temperatures for this example.

#### Step 2: Calculate weekly averages
You can then calculate the weekly averages using NumPy.

Here's a sample code to demonstrate this:

In [3]:
import numpy as np

# Step 1: Create a NumPy array with daily temperatures for a month
np.random.seed(0)  # For reproducibility
daily_temperatures = np.random.randint(low=15, high=30, size=30)  # Temperatures between 15 and 30 degrees

# Display the daily temperatures
print("Daily Temperatures for the Month:")
print(daily_temperatures)

# Step 2: Calculate weekly averages
# Reshape the array to 4 weeks (with 2 extra days that we will ignore)
weekly_temperatures = daily_temperatures[:28].reshape(4, 7)

# Calculate the average for each week
weekly_averages = np.mean(weekly_temperatures, axis=1)

# Display the weekly averages
print("\nWeekly Averages:")
print(weekly_averages)

Daily Temperatures for the Month:
[27 20 15 18 26 18 22 24 18 20 17 19 22 21 23 23 27 25 16 21 22 22 29 23
 16 20 24 28 23 24]

Weekly Averages:
[20.85714286 20.14285714 22.42857143 23.14285714]


#### Explanation:
1. Creating the Array: We use np.random.randint to generate random daily temperatures between 15 and 30 degrees for 30 days.
2. Reshape the Array: We reshape the array to a shape of (4, 7) to represent 4 weeks, using only the first 28 days.
3. Calculating Averages: We use np.mean along the first axis (rows) to calculate the average temperature for each week.
#### Output
When you run this code, you’ll get the daily temperatures and the average temperatures for each of the 4 weeks.